import { FormEvent, useMemo, useState } from 'react'
import { Mail, Pencil, Phone, Plus, Search, Trash2, UserRound, X } from 'lucide-react'

interface Contact { id: string; name: string; company?: string; email?: string; phone?: string; notes?: string; updatedAt: string }
const KEY = 'mt.contacts'
const load = (): Contact[] => { try { const value = JSON.parse(localStorage.getItem(KEY) ?? '[]'); return Array.isArray(value) ? value : [] } catch { return [] } }
const makeId = () => `contact-${Date.now()}-${Math.random().toString(36).slice(2, 7)}`
const input = 'w-full rounded-lg border border-neutral-200 bg-transparent px-3 py-2 text-sm outline-none focus:border-neutral-400 dark:border-neutral-700'

export default function Contacts() {
  const [contacts, setContacts] = useState<Contact[]>(load)
  const [query, setQuery] = useState('')
  const [draft, setDraft] = useState<Contact | null>(null)
  const visible = useMemo(() => contacts.filter((c) => `${c.name} ${c.company ?? ''} ${c.email ?? ''} ${c.notes ?? ''}`.toLowerCase().includes(query.trim().toLowerCase())), [contacts, query])
  const persist = (next: Contact[]) => { setContacts(next); localStorage.setItem(KEY, JSON.stringify(next)) }
  const save = (contact: Contact) => persist([contact, ...contacts.filter((c) => c.id !== contact.id)].sort((a, b) => b.updatedAt.localeCompare(a.updatedAt))); 
  return <div className="mx-auto w-full max-w-5xl space-y-6"><div className="flex flex-wrap items-center gap-3"><div className="mr-auto"><h2 className="text-2xl font-semibold tracking-tight">Kontakte</h2><p className="mt-1 text-sm text-neutral-500">Menschen und Ansprechpartner übersichtlich verwalten.</p></div><button type="button" onClick={() => setDraft({ id: makeId(), name: '', updatedAt: new Date().toISOString() })} className="flex items-center gap-1.5 rounded-lg bg-neutral-900 px-3 py-2 text-sm font-medium text-white hover:bg-neutral-700 dark:bg-white dark:text-neutral-900"><Plus className="size-4" />Kontakt</button></div><div className="relative"><Search className="absolute top-1/2 left-3 size-4 -translate-y-1/2 text-neutral-400" /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Kontakte durchsuchen…" className={`${input} pl-9`} /></div><section className="rounded-xl border border-neutral-200 bg-white dark:border-neutral-800 dark:bg-neutral-900"><ul className="divide-y divide-neutral-100 dark:divide-neutral-800">{visible.length === 0 && <li className="px-4 py-10 text-center text-sm text-neutral-500">Noch keine passenden Kontakte.</li>}{visible.map((contact) => <li key={contact.id} className="flex items-start gap-3 px-4 py-3"><span className="grid size-9 shrink-0 place-items-center rounded-full bg-neutral-100 text-neutral-500 dark:bg-neutral-800"><UserRound className="size-4" /></span><div className="min-w-0 flex-1"><div className="font-medium">{contact.name || 'Ohne Namen'}</div>{contact.company && <div className="text-xs text-neutral-500">{contact.company}</div>}<div className="mt-1 flex flex-wrap gap-x-4 gap-y-1 text-xs text-neutral-500">{contact.email && <a href={`mailto:${contact.email}`} className="flex items-center gap-1 hover:underline"><Mail className="size-3" />{contact.email}</a>}{contact.phone && <a href={`tel:${contact.phone}`} className="flex items-center gap-1 hover:underline"><Phone className="size-3" />{contact.phone}</a>}</div>{contact.notes && <p className="mt-1 text-xs text-neutral-600 dark:text-neutral-300">{contact.notes}</p>}</div><button type="button" onClick={() => setDraft(contact)} aria-label="Kontakt bearbeiten" className="rounded p-1.5 text-neutral-400 hover:bg-neutral-100 dark:hover:bg-neutral-800"><Pencil className="size-3.5" /></button><button type="button" onClick={() => persist(contacts.filter((c) => c.id !== contact.id))} aria-label="Kontakt löschen" className="rounded p-1.5 text-neutral-400 hover:bg-rose-50 hover:text-rose-600"><Trash2 className="size-3.5" /></button></li>)}</ul></section>{draft && <ContactDialog draft={draft} onClose={() => setDraft(null)} onSave={(value) => { save({ ...value, name: value.name.trim() || 'Ohne Namen', updatedAt: new Date().toISOString() }); setDraft(null) }} />}</div>
}

function ContactDialog({ draft, onClose, onSave }: { draft: Contact; onClose: () => void; onSave: (contact: Contact) => void }) {
  const [form, setForm] = useState(draft)
  const set = (key: keyof Contact, value: string) => setForm((current) => ({ ...current, [key]: value }))
  const submit = (event: FormEvent) => { event.preventDefault(); onSave(form) }
  return <div className="fixed inset-0 z-50 grid place-items-center bg-black/40 p-4" onMouseDown={(e) => { if (e.target === e.currentTarget) onClose() }}><form onSubmit={submit} onMouseDown={(e) => e.stopPropagation()} className="w-full max-w-md space-y-4 rounded-2xl border border-neutral-200 bg-white p-5 shadow-2xl dark:border-neutral-800 dark:bg-neutral-900"><div className="flex items-center"><h2 className="mr-auto text-sm font-semibold">Kontakt {draft.name ? 'bearbeiten' : 'anlegen'}</h2><button type="button" onClick={onClose} aria-label="Schließen" className="rounded p-1 text-neutral-400 hover:bg-neutral-100 dark:hover:bg-neutral-800"><X className="size-4" /></button></div><input autoFocus required value={form.name} onChange={(e) => set('name', e.target.value)} placeholder="Name" className={input} /><input value={form.company ?? ''} onChange={(e) => set('company', e.target.value)} placeholder="Firma / Organisation" className={input} /><div className="grid gap-2 sm:grid-cols-2"><input type="email" value={form.email ?? ''} onChange={(e) => set('email', e.target.value)} placeholder="E-Mail" className={input} /><input type="tel" value={form.phone ?? ''} onChange={(e) => set('phone', e.target.value)} placeholder="Telefon" className={input} /></div><textarea value={form.notes ?? ''} onChange={(e) => set('notes', e.target.value)} placeholder="Notiz" rows={3} className={input} /><div className="flex justify-end gap-2"><button type="button" onClick={onClose} className="rounded-lg border border-neutral-200 px-3 py-2 text-sm dark:border-neutral-700">Abbrechen</button><button type="submit" className="rounded-lg bg-neutral-900 px-3 py-2 text-sm font-medium text-white dark:bg-white dark:text-neutral-900">Speichern</button></div></form></div>
}
