import { FormEvent, useMemo, useState } from 'react'
import { Check, Flame, Plus, Trash2, X } from 'lucide-react'

type Frequency = 'daily' | 'weekly'
interface Habit { id: string; name: string; frequency: Frequency; completed: string[]; createdAt: string }
const KEY = 'mt.habits'
const load = (): Habit[] => { try { const value = JSON.parse(localStorage.getItem(KEY) ?? '[]'); return Array.isArray(value) ? value : [] } catch { return [] } }
const dateKey = (date = new Date()) => date.toISOString().slice(0, 10)
const makeId = () => `habit-${Date.now()}-${Math.random().toString(36).slice(2, 7)}`
const input = 'w-full rounded-lg border border-neutral-200 bg-transparent px-3 py-2 text-sm outline-none focus:border-neutral-400 dark:border-neutral-700'

export default function Habits() {
  const [habits, setHabits] = useState<Habit[]>(load)
  const [draft, setDraft] = useState<Habit | null>(null)
  const today = dateKey()
  const persist = (next: Habit[]) => { setHabits(next); localStorage.setItem(KEY, JSON.stringify(next)) }
  const toggle = (habit: Habit) => persist(habits.map((item) => item.id === habit.id ? { ...item, completed: item.completed.includes(today) ? item.completed.filter((day) => day !== today) : [...item.completed, today] } : item))
  const streak = (habit: Habit) => { let count = 0; const cursor = new Date(); while (habit.completed.includes(dateKey(cursor))) { count++; cursor.setDate(cursor.getDate() - (habit.frequency === 'weekly' ? 7 : 1)) } return count }
  const summary = useMemo(() => `${habits.filter((h) => h.completed.includes(today)).length} von ${habits.length} heute erledigt`, [habits, today])
  return <div className="mx-auto w-full max-w-4xl space-y-6"><div className="flex flex-wrap items-center gap-3"><div className="mr-auto"><h2 className="text-2xl font-semibold tracking-tight">Gewohnheiten</h2><p className="mt-1 text-sm text-neutral-500">Kleine Routinen sichtbar machen und dranbleiben.</p></div><button type="button" onClick={() => setDraft({ id: makeId(), name: '', frequency: 'daily', completed: [], createdAt: new Date().toISOString() })} className="flex items-center gap-1.5 rounded-lg bg-neutral-900 px-3 py-2 text-sm font-medium text-white hover:bg-neutral-700 dark:bg-white dark:text-neutral-900"><Plus className="size-4" />Gewohnheit</button></div><div className="rounded-xl border border-neutral-200 bg-white px-4 py-3 text-sm dark:border-neutral-800 dark:bg-neutral-900">{summary}</div><section className="rounded-xl border border-neutral-200 bg-white dark:border-neutral-800 dark:bg-neutral-900"><ul className="divide-y divide-neutral-100 dark:divide-neutral-800">{habits.length === 0 && <li className="px-4 py-10 text-center text-sm text-neutral-500">Noch keine Gewohnheiten angelegt.</li>}{habits.map((habit) => { const done = habit.completed.includes(today); return <li key={habit.id} className="flex items-center gap-3 px-4 py-3"><button type="button" onClick={() => toggle(habit)} aria-label={done ? 'Heute als offen markieren' : 'Heute abhaken'} aria-pressed={done} className={`grid size-8 shrink-0 place-items-center rounded-full border transition ${done ? 'border-emerald-500 bg-emerald-500 text-white' : 'border-neutral-300 text-transparent hover:border-emerald-400 dark:border-neutral-600'}`}><Check className="size-4" /></button><div className="min-w-0 flex-1"><div className={`text-sm font-medium ${done ? 'text-neutral-400 line-through' : ''}`}>{habit.name}</div><div className="text-xs text-neutral-500">{habit.frequency === 'daily' ? 'Täglich' : 'Wöchentlich'} · <Flame className="mr-0.5 inline size-3 text-amber-500" />{streak(habit)} {streak(habit) === 1 ? 'Tag' : 'Tage'} Serie</div></div><button type="button" onClick={() => setDraft(habit)} aria-label="Gewohnheit bearbeiten" className="rounded p-1.5 text-neutral-400 hover:bg-neutral-100 dark:hover:bg-neutral-800">✎</button><button type="button" onClick={() => persist(habits.filter((item) => item.id !== habit.id))} aria-label="Gewohnheit löschen" className="rounded p-1.5 text-neutral-400 hover:bg-rose-50 hover:text-rose-600"><Trash2 className="size-3.5" /></button></li>})}</ul></section>{draft && <HabitDialog draft={draft} onClose={() => setDraft(null)} onSave={(value) => { persist([value, ...habits.filter((item) => item.id !== value.id)]); setDraft(null) }} />}</div>
}

function HabitDialog({ draft, onClose, onSave }: { draft: Habit; onClose: () => void; onSave: (habit: Habit) => void }) { const [form, setForm] = useState(draft); const submit = (event: FormEvent) => { event.preventDefault(); onSave({ ...form, name: form.name.trim() || 'Gewohnheit' }) }; return <div className="fixed inset-0 z-50 grid place-items-center bg-black/40 p-4" onMouseDown={(e) => { if (e.target === e.currentTarget) onClose() }}><form onSubmit={submit} onMouseDown={(e) => e.stopPropagation()} className="w-full max-w-sm space-y-4 rounded-2xl border border-neutral-200 bg-white p-5 shadow-2xl dark:border-neutral-800 dark:bg-neutral-900"><div className="flex items-center"><h2 className="mr-auto text-sm font-semibold">Gewohnheit anlegen</h2><button type="button" onClick={onClose} aria-label="Schließen" className="rounded p-1 text-neutral-400 hover:bg-neutral-100 dark:hover:bg-neutral-800"><X className="size-4" /></button></div><input autoFocus required value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} placeholder="z. B. 20 Minuten lesen" className={input} /><select value={form.frequency} onChange={(e) => setForm({ ...form, frequency: e.target.value as Frequency })} className={input}><option value="daily">Täglich</option><option value="weekly">Wöchentlich</option></select><div className="flex justify-end gap-2"><button type="button" onClick={onClose} className="rounded-lg border border-neutral-200 px-3 py-2 text-sm dark:border-neutral-700">Abbrechen</button><button type="submit" className="rounded-lg bg-neutral-900 px-3 py-2 text-sm font-medium text-white dark:bg-white dark:text-neutral-900">Speichern</button></div></form></div> }
